VUM_USER_ACCOUNT = ENV["vum_user_account"]
VUM_SMS_CONVERSATION_KEY = ENV["vum_sms_conversation_key"]
VUM_SMS_API_TOKEN = ENV["vum_sms_api_token"]
VUM_USSD_CONVERSATION_KEY = ENV["vum_ussd_conversation_key"]
VUM_USSD_API_TOKEN = ENV["vum_ussd_api_token"]
VUM_USSD_CHANNEL = ENV["vum_ussd_channel"]
VUM_API_URL_BEGIN = ENV["vum_api_url_begin"]
VUM_API_URL_END = ENV["vum_api_url_end"]
