VUM_USER_ACCOUNT = ENV["vum_user_account"]
VUM_CONVERSATION_KEY = ENV["vum_conversation_key"]
VUM_API_TOKEN = ENV["vum_api_token"]
VUM_API_URL_BEGIN = ENV["vum_api_url_begin"]
VUM_API_URL_END = ENV["vum_api_url_end"]
